# Generated by Django 3.1.13 on 2021-11-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='transport',
            field=models.CharField(choices=[('Walk', 'Walk'), ('Walk', 'Bicycle'), ('Bus', 'Bus'), ('Car', 'Car'), ('Plane', 'Plane'), ('Helicopter', 'Helicopter')], default='Walk', max_length=100, null=True, verbose_name='Transport'),
        ),
    ]
